# -*- coding: utf-8 -*-
"""Uber_Lift_XGBoost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kpKD-FuegNWSKsZucE4lSXhA8y7s2Ky_
"""

!pip -q install xgboost

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, ConfusionMatrixDisplay
from xgboost import XGBClassifier

#1. Loading the Data

cab_df = pd.read_csv("cab_rides.csv")
weather_df = pd.read_csv("weather.csv")

#2. Cleaning up data and converting conflicting timestamps

cab_df = cab_df.dropna(subset=["price"]).copy()

#Converting timestamps
cab_df["datetime"] = pd.to_datetime(cab_df["time_stamp"], unit="ms", errors="coerce")
weather_df["datetime"] = pd.to_datetime(weather_df["time_stamp"], unit="s", errors="coerce")

cab_df = cab_df.dropna(subset=["datetime"])
weather_df = weather_df.dropna(subset=["datetime"])

#Sorting to merge later
cab_df = cab_df.sort_values(["source", "datetime"])
weather_df = weather_df.sort_values(["location", "datetime"])

#3. Merging

#Dropping missing keys
cab_df = cab_df.dropna(subset=["datetime", "source"]).copy()
weather_df = weather_df.dropna(subset=["datetime", "location"]).copy()

#Checking types
cab_df["datetime"] = pd.to_datetime(cab_df["datetime"], errors="coerce")
weather_df["datetime"] = pd.to_datetime(weather_df["datetime"], errors="coerce")

cab_df["source"] = cab_df["source"].astype(str)
weather_df["location"] = weather_df["location"].astype(str)

#Dropping invalid rows
cab_df = cab_df.dropna(subset=["datetime", "source"]).copy()
weather_df = weather_df.dropna(subset=["datetime", "location"]).copy()

#Sorting by datetime, then grouping by column
cab_df = cab_df.sort_values(["datetime", "source"]).reset_index(drop=True)
weather_df = weather_df.sort_values(["datetime", "location"]).reset_index(drop=True)

merged_df = pd.merge_asof(
    cab_df,
    weather_df,
    left_on="datetime",
    right_on="datetime",
    left_by="source",
    right_by="location",
    direction="nearest",
    tolerance=pd.Timedelta("2H")
)

#4. Feature engineering
merged_df["hour"] = merged_df["datetime"].dt.hour
merged_df["day"] = merged_df["datetime"].dt.day
merged_df["month"] = merged_df["datetime"].dt.month
merged_df["dayofweek"] = merged_df["datetime"].dt.dayofweek
merged_df["is_weekend"] = (merged_df["dayofweek"] >= 5).astype(int)

#5. Labelling the class (price)

q1 = merged_df["price"].quantile(0.33)
q2 = merged_df["price"].quantile(0.67)

def price_category(p):
    if p <= q1:
        return "low"
    elif p <= q2:
        return "medium"
    else:
        return "high"

merged_df["price_category"] = merged_df["price"].apply(price_category)

#6. Features using
features = [
    "distance", "cab_type", "name", "source", "destination",
    "hour", "day", "month", "dayofweek", "is_weekend",
    "surge_multiplier", "temp", "clouds", "pressure",
    "rain", "humidity", "wind"
]

features = [f for f in features if f in merged_df.columns]

X = merged_df[features]
y = merged_df["price_category"]

#7. Preprocessing
numeric_features = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_features = X.select_dtypes(include=["object", "bool"]).columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        ("num", Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ]), numeric_features),

        ("cat", Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore"))
        ]), categorical_features)
    ]
)

# Encode labels for XGBoost
le = LabelEncoder()
y_encoded = le.fit_transform(y)

#8. Train, test split


X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

#9. Training XGBoost

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="mlogloss",
        random_state=42
    ))
])

print("Training the model...")
model.fit(X_train, y_train)

#10. Eval
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average="macro")

print("\nXGBoost Results:")
print("Accuracy:", accuracy)
print("Macro-F1:", f1)

#11. Confidence interbals

def bootstrap_ci(y_true, y_pred, metric, n=300):
    rng = np.random.default_rng(42)
    scores = []
    for _ in range(n):
        idx = rng.integers(0, len(y_true), len(y_true))
        scores.append(metric(y_true[idx], y_pred[idx]))
    return np.percentile(scores, [2.5, 97.5])

acc_ci = bootstrap_ci(y_test, y_pred, accuracy_score)
f1_ci = bootstrap_ci(y_test, y_pred, lambda yt, yp: f1_score(yt, yp, average='macro'))

print("\n95% Confidence Intervals:")
print("Accuracy CI:", acc_ci)
print("Macro-F1 CI:", f1_ci)

#12. confusion matrix

labels = le.classes_

cm = confusion_matrix(y_test, y_pred, normalize="true")

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
disp.plot(values_format=".2f")
plt.title("Normalized Confusion Matrix (XGBoost)")
plt.show()