# -*- coding: utf-8 -*-
"""Uber and Lift Linear Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvouA2yOW0euLCa9xieH9NNKb5Ef8TYn
"""

import kagglehub

path = kagglehub.dataset_download("ravi72munde/uber-lyft-cab-prices")
print("Path to dataset files:", path)

import os

os.listdir(path)

import pandas as pd
import os

# Find correct file path
for root, dirs, files in os.walk(path):
    for file in files:
        if file == "cab_rides.csv":
            full_path = os.path.join(root, file)

print(full_path)

cab_data.info()

# Only drop rows where price is missing
cab_data = cab_data.dropna(subset=["price"])

# Drop unnecessary columns
cab_data = cab_data.drop(columns=[
    "id", "product_id", "timestamp", "datetime"
], errors="ignore")

X = cab_data.drop("price", axis=1)
y = cab_data["price"]

X = pd.get_dummies(X, drop_first=True)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)

import numpy as np

def bootstrap_ci(y_true, y_pred, n_bootstrap=1000):
    errors = []
    n = len(y_true)

    for _ in range(n_bootstrap):
        indices = np.random.choice(range(n), n, replace=True)
        error = np.mean(np.abs(y_true.iloc[indices] - y_pred[indices]))
        errors.append(error)

    return np.percentile(errors, [2.5, 97.5])

ci = bootstrap_ci(y_test.reset_index(drop=True), y_pred)
print("95% CI for MAE:", ci)

# IMPORT LIBRARIES
import kagglehub
import pandas as pd
import numpy as np
import os

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# DOWNLOAD DATASET
path = kagglehub.dataset_download("ravi72munde/uber-lyft-cab-prices")

# Locate cab_rides.csv
for root, dirs, files in os.walk(path):
    for file in files:
        if file == "cab_rides.csv":
            full_path = os.path.join(root, file)

print("Dataset path:", full_path)

# LOAD DATA
cab_data = pd.read_csv(full_path)

print("\nFirst few rows:")
print(cab_data.head())

print("\nDataset info:")
print(cab_data.info())


# DATA CLEANING
# Drop rows where price is missing
cab_data = cab_data.dropna(subset=["price"])

# Drop unnecessary columns
cab_data = cab_data.drop(columns=[
    "id", "product_id", "timestamp", "datetime"
], errors="ignore")

# FEATURE SELECTION
X = cab_data.drop("price", axis=1)
y = cab_data["price"]

# Convert categorical variables
X = pd.get_dummies(X, drop_first=True)

print("\nFeature shape after encoding:", X.shape)

# TRAIN-TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# SCALING
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# TRAIN MODEL (LINEAR REGRESSION)
model = LinearRegression()
model.fit(X_train, y_train)

# PREDICTIONS
y_pred = model.predict(X_test)


# EVALUATION METRICS
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("\n===== MODEL PERFORMANCE =====")
print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)

# CONFIDENCE INTERVAL (BOOTSTRAP)
def bootstrap_ci(y_true, y_pred, n_bootstrap=1000):
    errors = []
    n = len(y_true)

    y_true = y_true.reset_index(drop=True)

    for _ in range(n_bootstrap):
        indices = np.random.choice(range(n), n, replace=True)
        error = np.mean(np.abs(y_true.iloc[indices] - y_pred[indices]))
        errors.append(error)

    return np.percentile(errors, [2.5, 97.5])

ci = bootstrap_ci(y_test, y_pred)

print("\n95% Confidence Interval for MAE:", ci)

!pip install xgboost

from xgboost import XGBRegressor

# TRAIN MODEL (XGBOOST)
xgb_model = XGBRegressor(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train, y_train)

# PREDICTIONS
y_pred_xgb = xgb_model.predict(X_test)

# EVALUATION METRICS
mae_xgb = mean_absolute_error(y_test, y_pred_xgb)
rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_xgb))
r2_xgb = r2_score(y_test, y_pred_xgb)

print("\n===== XGBOOST PERFORMANCE =====")
print("MAE:", mae_xgb)
print("RMSE:", rmse_xgb)
print("R²:", r2_xgb)

def bootstrap_ci(y_true, y_pred, n_bootstrap=1000):
    errors = []
    n = len(y_true)

    y_true = y_true.reset_index(drop=True)
    y_pred = pd.Series(y_pred)

    for _ in range(n_bootstrap):
        indices = np.random.choice(range(n), n, replace=True)
        error = np.mean(np.abs(
            y_true.iloc[indices].values - y_pred.iloc[indices].values
        ))
        errors.append(error)

    return np.percentile(errors, [2.5, 97.5])

ci_xgb = bootstrap_ci(y_test, y_pred_xgb)

print("\n95% Confidence Interval for MAE (XGBoost):", ci_xgb)

from sklearn.metrics import confusion_matrix

def categorize_price(p):
    if p < 10:
        return "Low"
    elif p < 25:
        return "Medium"
    else:
        return "High"

y_test_cat = y_test.apply(categorize_price)
y_pred_xgb_cat = pd.Series(y_pred_xgb).apply(categorize_price)

cm_xgb = confusion_matrix(y_test_cat, y_pred_xgb_cat, labels=["Low","Medium","High"])

cm_xgb_normalized = cm_xgb.astype('float') / cm_xgb.sum(axis=1)[:, np.newaxis]

print("\nNormalized Confusion Matrix (XGBoost):")
print(cm_xgb_normalized)

import matplotlib.pyplot as plt

importances = xgb_model.feature_importances_
features = X.columns

feat_imp = pd.DataFrame({
    "Feature": features,
    "Importance": importances
}).sort_values(by="Importance", ascending=False)

print("\nTop Features (XGBoost):")
print(feat_imp.head(10))

plt.figure()
plt.barh(feat_imp["Feature"][:10], feat_imp["Importance"][:10])
plt.gca().invert_yaxis()
plt.title("Top 10 Feature Importances")
plt.show()